### PR TITLE
remove checks

### PR DESCRIPTION
**Pull request by sciunto**
Sorry, I confused myself at some point.

On my machine, this code passes the tests as well as your version. If there is a case for which this code is wrong, then it needs additional tests.

### CODE REVIEW

**Comment by rfezzani** [comment]
I added to [test_invalid_use_quantiles](https://github.com/scikit-image/scikit-image/pull/4437/files#diff-16d4fd31a36ab89fe7472984c682cdddR108) the case reported in #4282. This test case should fail with this PR.

**Comment by sciunto** [comment]
I cloned your branch, the test you added is included and my code passes your test. Can you have a try please? (sorry to be difficult)

**Comment by rfezzani** [comment]
Ooooh, My bad, sorry! :-)
These lines are no more necessary since (As you said) the threshold are no more touched after the first checks...
I was confused because of my refactoring in #4342...
You are absolutely right, these lines can be safely removed... Do I let you fill a PR? I would be happy to accept it ;-)

**Comment by sciunto** [comment]
I'll do :) I think your confusion confused me, which confused you. Glad we find the exit of the spiral :D

**Pull request closed without merging**
